# Generated by Django 5.1.2 on 2025-01-30 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_defaultholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiDefaultHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='dashboard.employee')),
            ],
        ),
    ]
