# Generated by Django 5.1.2 on 2025-01-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_messagebox_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rejected_count',
            field=models.IntegerField(default=0),
        ),
    ]
