# Generated by Django 5.1.2 on 2025-01-30 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_task_rejected_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistoryKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('extended_date', models.DateField(blank=True, null=True)),
                ('revision_count', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('action_taken', models.CharField(choices=[('Approved', 'Approved'), ('Deleted', 'Deleted')], max_length=50)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history', to='dashboard.employee')),
                ('task_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.employee')),
            ],
        ),
    ]
