# Generated by Django 5.1.2 on 2025-01-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_taskhistorykeeper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistorykeeper',
            name='task_owner',
        ),
        migrations.AlterField(
            model_name='taskhistorykeeper',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.employee'),
        ),
    ]
