# Generated by Django 5.1.2 on 2025-01-31 06:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_taskhistorykeeper_task_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEmployeeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('month_name', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('total_workdays', models.PositiveIntegerField(default=0)),
                ('total_present_days', models.PositiveIntegerField(default=0)),
                ('total_absent_days', models.PositiveIntegerField(default=0)),
                ('total_holidays_taken', models.PositiveIntegerField(default=0)),
                ('total_default_holidays', models.PositiveIntegerField(default=0)),
                ('total_occasional_holidays', models.PositiveIntegerField(default=0)),
                ('total_assigned_tasks', models.PositiveIntegerField(default=0)),
                ('total_approved_tasks', models.PositiveIntegerField(default=0)),
                ('assigned_task_ids', models.TextField(blank=True, null=True)),
                ('approved_task_ids', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
