# Generated by Django 5.1.2 on 2025-01-31 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_monthlyemployeereport_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistorykeeper',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.employee'),
        ),
    ]
