# Generated by Django 5.1.2 on 2025-01-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_taskhistorykeeper_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistorykeeper',
            name='assigned_to',
            field=models.CharField(default='employee_name', max_length=50),
        ),
    ]
