# Generated by Django 5.1.2 on 2025-01-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_taskhistorykeeper_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyEmployeeReport',
        ),
    ]
