# Generated by Django 5.1.2 on 2025-02-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='quit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
