# Generated by Django 5.1.2 on 2025-02-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_attendance_quit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('employee_id', models.PositiveIntegerField()),
                ('employee_name', models.CharField(max_length=50)),
                ('total_workdays', models.PositiveIntegerField()),
                ('total_present_days', models.PositiveIntegerField()),
                ('total_holidays_taken', models.PositiveIntegerField()),
                ('total_occasional_holidays', models.PositiveIntegerField()),
                ('total_task_assigned', models.PositiveIntegerField(default=0)),
                ('assigned_task_ids_with_title', models.TextField(blank=True, null=True)),
                ('total_task_completed', models.PositiveIntegerField(default=0)),
                ('completed_task_ids_with_title', models.TextField(blank=True, null=True)),
                ('employee_present_status', models.CharField(choices=[('Running', 'Running'), ('Removed', 'Removed')], default='Running', max_length=20)),
            ],
        ),
    ]
