# Generated by Django 5.1.2 on 2025-02-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_monthsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthsummary',
            name='month',
            field=models.CharField(default='February', max_length=10),
        ),
        migrations.AlterField(
            model_name='monthsummary',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
