# Generated by Django 5.1.2 on 2025-02-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_monthsummary_month_alter_monthsummary_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_processed_month', models.CharField(blank=True, max_length=10, null=True)),
                ('last_processed_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
