# Generated by Django 5.1.2 on 2025-02-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_position_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
