# Generated by Django 5.1.2 on 2025-02-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_employee_position_delete_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Fresher', max_length=100),
        ),
    ]
