# Generated by Django 5.1.2 on 2025-02-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_employeejoinandout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeejoinandout',
            old_name='date',
            new_name='joining_date',
        ),
        migrations.RenameField(
            model_name='employeejoinandout',
            old_name='leave',
            new_name='leaving_date',
        ),
    ]
