# Generated by Django 5.1.2 on 2025-02-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_rename_date_employeejoinandout_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthsummary',
            name='joining_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthsummary',
            name='leaving_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EmployeeJoinAndOut',
        ),
    ]
